[project]
name = "pyton"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.2.0",
    "scikit-learn>=1.5.0",
    "python-dotenv>=1.1.0",
    "openai>=1.91.0",
    "openai-agents>=0.0.19",
    "openpyxl>=3.1.5",
    "bs4>=0.0.2",
    "google-adk>=1.1.1",
    "google-genai==1.16.1",
    "google-generativeai==0.8.5",
    "playwright>=1.52.0",
    "nest_asyncio>=1.6.0",
    "beautifulsoup4>=4.14.2",
    "selenium>=4.36.0",
    "webdriver-manager>=4.0.2",
    "chromadb>=1.0.13",
    "sentence-transformers>=5.1.2",
    "langchain>=1.0.2",
    "langchain-community>=0.4",
    "gradio>=5.49.1",
    "transformers>=4.57.1",
    "diffusers>=0.35.2",
    "torch>=2.9.0",
    "accelerate>=1.11.0",
    "safetensors>=0.6.2",
    "librosa>=0.11.0"
]
